//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstaSport.Services.Data.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InstaSport.Services.Data.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        public static string CreateGameButton {
            get {
                return ResourceManager.GetString("CreateGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        public static string CreateGameNavItemLabel {
            get {
                return ResourceManager.GetString("CreateGameNavItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        public static string CreateGameTitle {
            get {
                return ResourceManager.GetString("CreateGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time: .
        /// </summary>
        public static string DateTimeLabel {
            get {
                return ResourceManager.GetString("DateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsButtonLabel {
            get {
                return ResourceManager.GetString("DetailsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Games by Location.
        /// </summary>
        public static string FilterGamesByLocationButton {
            get {
                return ResourceManager.GetString("FilterGamesByLocationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Games By Sport.
        /// </summary>
        public static string FilterGamesBySportButton {
            get {
                return ResourceManager.GetString("FilterGamesBySportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string GamesNavItemLabel {
            get {
                return ResourceManager.GetString("GamesNavItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        public static string JoinGameLabel {
            get {
                return ResourceManager.GetString("JoinGameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Game.
        /// </summary>
        public static string LeaveGameLabel {
            get {
                return ResourceManager.GetString("LeaveGameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: .
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string LocationsLabel {
            get {
                return ResourceManager.GetString("LocationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string LocationsNavItemLabel {
            get {
                return ResourceManager.GetString("LocationsNavItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as: .
        /// </summary>
        public static string LoggedInAsLabel {
            get {
                return ResourceManager.GetString("LoggedInAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginNavItemLabel {
            get {
                return ResourceManager.GetString("LoginNavItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Players.
        /// </summary>
        public static string MaxPlayersLabel {
            get {
                return ResourceManager.GetString("MaxPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Players.
        /// </summary>
        public static string MinPlayersLabel {
            get {
                return ResourceManager.GetString("MinPlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match!.
        /// </summary>
        public static string PasswordsDontMatchMessage {
            get {
                return ResourceManager.GetString("PasswordsDontMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players: .
        /// </summary>
        public static string PlayersLabel {
            get {
                return ResourceManager.GetString("PlayersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Player.
        /// </summary>
        public static string RatePlayerTitle {
            get {
                return ResourceManager.GetString("RatePlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating: .
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterNavItemLabel {
            get {
                return ResourceManager.GetString("RegisterNavItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport: .
        /// </summary>
        public static string SportLabel {
            get {
                return ResourceManager.GetString("SportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string SportsLabel {
            get {
                return ResourceManager.GetString("SportsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        public static string SportsNavItemLabel {
            get {
                return ResourceManager.GetString("SportsNavItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username \ Email:.
        /// </summary>
        public static string UsernameEmailLabel {
            get {
                return ResourceManager.GetString("UsernameEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        public static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password!.
        /// </summary>
        public static string WrongUsernameOrPasswordMessage {
            get {
                return ResourceManager.GetString("WrongUsernameOrPasswordMessage", resourceCulture);
            }
        }
    }
}
